### ISSUE TITLE
Usage w/ "Auto-Away"

### ISSUE THREAD

**Issue by iwoloschin** [MilhouseVH/autoaway.py#2]
Just bought a Nest and got it integrated with my Android and my wife's iPhone, all in under a couple of hours.  This is pretty awesome, thanks!  A couple of questions though.

1) Should I disable the "auto-away" functionality of the Nest?  If I'm using my cellphones to determine "awayness" then I think that should be off, right?
2) Your script appears to only handle away/here changes, do you let your Nest make other temperature decisions (like turning down at night, even though you're "Here")?

Otherwise everything works well and seems straightforward.  This is great since my Nest is in a mediocre position to determine awayness, but by watching for cellphones it fixes that really quickly.

**Comment by MilhouseVH** [comment]
1) I think so
2) I don't actually have a Nest - yet - as they're not (officially) available here in the UK. If/when I do get a Nest it will be behind a door, hence why I knocked up this script.

The required logic that people wanted seemed to be just the automation of here/away status, so I'm assuming that people disable auto-away entirely, and then leave the Nest to function normally while they are "here".

**Comment by iwoloschin** [comment]
Well, in that case, I'll do some experimenting and report back in about a week once it's had some time to learn.

**Comment by MilhouseVH** [comment]
That would be appreciated, and if any changes are necessary then they'll get made! :)
