### ISSUE TITLE
ARP and PINGs not working iOS

### ISSUE THREAD

**Issue by geah70** [MilhouseVH/autoaway.py#5]
Hello,  I am attempt to get this working on my iOS device but I am having issues:
1) My iPhone has a static IP address when on WiFi but I noticed that the ARP cache entry for my iPhone isn't removed from the ARP cache automatically when I disable my WiFi on the iPhone.  The ARP cache entry is only removed when I attempt to PING the static IP of the phone
2) Since ARP was not working, I attempted to use the --noarp paramter.  However, the iPhone doesn't respond to PING when it goes to sleep mode.

How did everyone else get their autoaway script working?  I was looking at the app called Skylark but it isn't Android compatible and I intend to Android and iPhones at my house.  

Thanks in advance.

**Comment by MilhouseVH** [comment]
If the phone stops responding to ping even though it's still on, there's really not very much I can do as that's pretty much an essential requirement for the script to function. I think you'll need to find another solution that runs on the phone itself (or maybe just find a better phone..).
