### ISSUE TITLE
Offpeak triggers 'away'

### ISSUE THREAD

**Issue by fbradyirl** [MilhouseVH/autoaway.py#6]
It would be a nice option to have offpeak trigger 'away' and end offpeak trigger 'here'.

For example, for me, it would set the Nest to away, plus enable motion detection on my CCTV, at 1am and reverse those at 6am.

Make sense? Would be a nice boolean to add as a param.

**Comment by MilhouseVH** [comment]
You might as well schedule a cron job that does the same thing.
